-- ALTER SESSION for 12c only
--alter session set "_ORACLE_SCRIPT"=true;

-- USER SQL
CREATE USER refimpl IDENTIFIED BY refimpl ;

-- QUOTAS

-- ROLES
GRANT "DBA" TO refimpl WITH ADMIN OPTION;
ALTER USER refimpl DEFAULT ROLE "DBA";

-- SYSTEM PRIVILEGES
